<div class="grid_17" id="isi1">

<h3>REGISTRASI MEMBER BARU</h3>
<table>
<tr>
<?php
echo form_open_multipart("user/towait"); 
?>
<td>Username</td><td>:</td><td><input type="text" id="reg" name="username"  required="required"/></td></tr>
<tr><td>Password</td><td>:</td><td><input type="password" name="password" required="required"/></td></tr>
<tr><td>Konfirmasi Password</td><td>:</td><td><input type="password" name="konfirmpass" required="required"/></td></tr>

<tr><td><br /><br /></td></tr>
<tr><td>NPWP</td><td>:</td><td><input type="text" name="npwp" required="required"/></td></tr>
<tr><td>Nama Perusahaan</td><td>:</td><td><input type="text" name="perusahaan" required="required"/></td></tr>
<tr><td>Alamat perusahaan</td><td>:</td><td><textarea name="alamat"  required="required"/></textarea></td></tr>
<tr><td>Propinsi perusahaan</td><td>:</td><td>
<select name="propinsi" >
<option value="pilih propinsi" />-----pilih propinsi-----</option>
<option value="Nanggroe Aceh Darussalam">Nanggroe Aceh Darussalam</option>
	<option value="Sumatera Utara">Sumatera Utara</option>
	<option value="Sumatera Barat">Sumatera Barat</option>
	<option value="Riau">Riau</option>
	<option value="Kepulauan Riau">Kepulauan Riau</option>
	<option value="Jambi">Jambi</option>
	<option value="Bengkulu">Bengkulu</option>
	<option value="Sumatera Selatan">Sumatera Selatan</option>
	<option value="Bangka-Belitung">Bangka-Belitung</option>
	<option value="Lampung">Lampung</option>
	<option value="DKI Jakarta">DKI Jakarta</option>
	<option value="Banten">Banten</option>
	<option value="Jawa Barat">Jawa Barat</option>
	<option value="Jawa Tengah">Jawa Tengah</option>
	<option value="D.I. Yogyakarta">D.I. Yogyakarta</option>
	<option value="Jawa Timur">Jawa Timur</option>
	<option value="Bali">Bali</option>
	<option value="Nusa Tenggara Barat">Nusa Tenggara Barat</option>
	<option value="Nusa Tenggara Timur">Nusa Tenggara Timur</option>
	<option value="Kalimantan Barat">Kalimantan Barat</option>
	<option value="Kalimantan Tengah">Kalimantan Tengah</option>
	<option value="Kalimantan Selatan">Kalimantan Selatan</option>
	<option value="Kalimantan Timur">Kalimantan Timur</option>
	<option value="Sulawesi Utara">Sulawesi Utara</option>
	<option value="Gorontalo">Gorontalo</option>
	<option value="Sulawesi Tengah">Sulawesi Tengah</option>
	<option value="Sulawesi Tenggara">Sulawesi Tenggara</option>
	<option value="Sulawesi Selatan">Sulawesi Selatan</option>
	<option value="Sulawesi Barat">Sulawesi Barat</option>
	<option value="Maluku">Maluku</option>
	<option value="Maluku Utara">Maluku Utara</option>
	<option value="Papua">Papua</option>
	<option value="Papua Barat">Papua Barat</option>
</select>
</td></tr>
<tr><td>Kota perusahaan</td><td>:</td><td>
<select name="kota">
<option value="pilih kota" />-----pilih kota-----</option>
<option value="2704">BANGKA BARAT</option>
	<option value="2702">BANGKA INDUK</option>
	<option value="2706">BANGKA SELATAN</option>
	<option value="2705">BANGKA TENGAH</option>
	<option value="1110">BANYUASIN</option>
	<option value="1009">BATANGHARI</option>
	<option value="2703">BELITUNG BARAT</option>
	<option value="2707">BELITUNG TIMUR</option>
	<option value="1204">BENGKULU SELATAN</option>
	<option value="1203">BENGKULU UTARA</option>
	<option value="1003">BUNGO</option>
	<option value="724">HUMBANG HASUDUTAN</option>
	<option value="2427">KAB SUMBA BARAT DAYA</option>
	<option value="2604">KABUPATEN  JAYAWIJAYA</option>
	<option value="603">KABUPATEN ACEH BARAT</option>
	<option value="618">KABUPATEN ACEH BARAT DAYA</option>
	<option value="604">KABUPATEN ACEH BESAR</option>
	<option value="617">KABUPATEN ACEH JAYA</option>
	<option value="610">KABUPATEN ACEH JEUMPA</option>
	<option value="605">KABUPATEN ACEH SELATAN</option>
	<option value="620">KABUPATEN ACEH TAMIANG</option>
	<option value="606">KABUPATEN ACEH TENGAH</option>
	<option value="607">KABUPATEN ACEH TENGGARA</option>
	<option value="608">KABUPATEN ACEH TIMUR</option>
	<option value="609">KABUPATEN ACEH UTARA</option>
	<option value="806">KABUPATEN AGAM</option>
	<option value="2415">KABUPATEN ALOR</option>
	<option value="707">KABUPATEN ASAHAN</option>
	<option value="2618">KABUPATEN ASMAT</option>
	<option value="2211">KABUPATEN BADUNG</option>
	<option value="1412">KABUPATEN BALANGAN</option>
	<option value="224">KABUPATEN BANDUNG</option>
	<option value="2005">KABUPATEN BANGGAI DARATAN</option>
	<option value="433">KABUPATEN BANGKALAN</option>
	<option value="2007">KABUPATEN BANGKEP</option>
	<option value="2213">KABUPATEN BANGLI</option>
	<option value="1402">KABUPATEN BANJAR</option>
	<option value="323">KABUPATEN BANJARNEGARA</option>
	<option value="1803">KABUPATEN BANTAENG</option>
	<option value="503">KABUPATEN BANTUL</option>
	<option value="320">KABUPATEN BANYUMAS</option>
	<option value="432">KABUPATEN BANYUWANGI</option>
	<option value="1407">KABUPATEN BARITO KUALA</option>
	<option value="1611">KABUPATEN BARITO SELATAN</option>
	<option value="1612">KABUPATEN BARITO TIMUR</option>
	<option value="1613">KABUPATEN BARITO UTARA</option>
	<option value="1414">KABUPATEN BARITO UTARA</option>
	<option value="1804">KABUPATEN BARRU</option>
	<option value="314">KABUPATEN BATANG</option>
	<option value="452">KABUPATEN BATU</option>
	<option value="726">KABUPATEN BATUBARA</option>
	<option value="220">KABUPATEN BEKASI</option>
	<option value="2414">KABUPATEN BELU</option>
	<option value="621">KABUPATEN BENER MERIAH</option>
	<option value="903">KABUPATEN BENGKALIS</option>
	<option value="1503">KABUPATEN BENGKAYANG</option>
	<option value="1705">KABUPATEN BERAU</option>
	<option value="2605">KABUPATEN BIAK NUMFOR</option>
	<option value="2314">KABUPATEN BIMA</option>
	<option value="461">KABUPATEN BLITAR</option>
	<option value="311">KABUPATEN BLORA</option>
	<option value="215">KABUPATEN BOGOR</option>
	<option value="414">KABUPATEN BOJONEGORO</option>
	<option value="2103">KABUPATEN BOLMONG</option>
	<option value="1907">KABUPATEN BOMBANA</option>
	<option value="428">KABUPATEN BONDOWOSO</option>
	<option value="1805">KABUPATEN BONE</option>
	<option value="2905">KABUPATEN BONE BOLANGO</option>
	<option value="2616">KABUPATEN BOVEN DIGOEL</option>
	<option value="330">KABUPATEN BOYOLALI</option>
	<option value="507">KABUPATEN BOYOLALI</option>
	<option value="318">KABUPATEN BREBES</option>
	<option value="2903">KABUPATEN BUALEMO</option>
	<option value="2216">KABUPATEN BULELENG</option>
	<option value="1806">KABUPATEN BULUKUMBA</option>
	<option value="1708">KABUPATEN BULUNGAN</option>
	<option value="2002">KABUPATEN BUOL</option>
	<option value="2504">KABUPATEN BURU</option>
	<option value="1903">KABUPATEN BUTON</option>
	<option value="229">KABUPATEN CIAMIS</option>
	<option value="218">KABUPATEN CIANJUR</option>
	<option value="319">KABUPATEN CILACAP</option>
	<option value="231">KABUPATEN CIREBON</option>
	<option value="708">KABUPATEN DAIRI</option>
	<option value="709">KABUPATEN DELI SERDANG</option>
	<option value="305">KABUPATEN DEMAK</option>
	<option value="817">KABUPATEN DHARMAS RAYA</option>
	<option value="2315">KABUPATEN DOMPU</option>
	<option value="2004">KABUPATEN DONGGALA</option>
	<option value="1115">KABUPATEN EMPAT LAWANG</option>
	<option value="2418">KABUPATEN ENDE</option>
	<option value="1807">KABUPATEN ENREKANG</option>
	<option value="3304">KABUPATEN FAK FAK</option>
	<option value="2417">KABUPATEN FLORES TIMUR</option>
	<option value="226">KABUPATEN GARUT</option>
	<option value="619">KABUPATEN GAYO LUWES</option>
	<option value="2212">KABUPATEN GIANYAR</option>
	<option value="1610">KABUPATEN GN MAS KUALA KU</option>
	<option value="505">KABUPATEN GN. KIDUL</option>
	<option value="2902">KABUPATEN GORONTALO</option>
	<option value="1808">KABUPATEN GOWA</option>
	<option value="411">KABUPATEN GRESIK</option>
	<option value="310">KABUPATEN GROBOGAN</option>
	<option value="3007">KABUPATEN HALMAHERA BARAT</option>
	<option value="3003">KABUPATEN HALMAHERA SELATA</option>
	<option value="3008">KABUPATEN HALMAHERA TENGAH</option>
	<option value="3005">KABUPATEN HALMAHERA TIMUR</option>
	<option value="3002">KABUPATEN HALMAHERA UTARA</option>
	<option value="1410">KABUPATEN HULU SEI SELATA</option>
	<option value="1413">KABUPATEN HULU SEI TENGAH</option>
	<option value="1411">KABUPATEN HULU SEI UTARA</option>
	<option value="905">KABUPATEN INDRAGIRI HILIR</option>
	<option value="904">KABUPATEN INDRAGIRI HULU</option>
	<option value="233">KABUPATEN INDRAMAYU</option>
	<option value="2602">KABUPATEN JAYAPURA</option>
	<option value="427">KABUPATEN JEMBER</option>
	<option value="2218">KABUPATEN JEMBRANA</option>
	<option value="1809">KABUPATEN JENEPONTO</option>
	<option value="307">KABUPATEN JEPARA</option>
	<option value="413">KABUPATEN JOMBANG</option>
	<option value="3305">KABUPATEN KAIMANA</option>
	<option value="906">KABUPATEN KAMPAR</option>
	<option value="1608">KABUPATEN KAPUAS</option>
	<option value="1508">KABUPATEN KAPUAS HULU</option>
	<option value="332">KABUPATEN KARANGANYAR</option>
	<option value="509">KABUPATEN KARANGANYAR</option>
	<option value="2215">KABUPATEN KARANGASEM</option>
	<option value="221">KABUPATEN KARAWANG</option>
	<option value="3102">KABUPATEN KARIMUN</option>
	<option value="710">KABUPATEN KARO</option>
	<option value="1603">KABUPATEN KATINGAN</option>
	<option value="321">KABUPATEN KEBUMEN</option>
	<option value="441">KABUPATEN KEDIRI</option>
	<option value="2611">KABUPATEN KEEROM</option>
	<option value="304">KABUPATEN KENDAL</option>
	<option value="807">KABUPATEN KEP. MENTAWAI</option>
	<option value="106">KABUPATEN KEP.SERIBU</option>
	<option value="2506">KABUPATEN KEPULAUAN ARU</option>
	<option value="3004">KABUPATEN KEPULAUAN SILA</option>
	<option value="1507">KABUPATEN KETAPANG</option>
	<option value="510">KABUPATEN KLATEN</option>
	<option value="333">KABUPATEN KLATEN</option>
	<option value="2214">KABUPATEN KLUNGKUNG</option>
	<option value="1904">KABUPATEN KOLAKA</option>
	<option value="1909">KABUPATEN KOLAKA UTARA</option>
	<option value="1902">KABUPATEN KONAWE</option>
	<option value="1908">KABUPATEN KONAWE SELATAN</option>
	<option value="1911">KABUPATEN KONAWE UTARA</option>
	<option value="1405">KABUPATEN KOTABARU</option>
	<option value="1605">KABUPATEN KOTAWARINGIN BA</option>
	<option value="1602">KABUPATEN KOTAWARINGIN TI</option>
	<option value="907">KABUPATEN KUANTAN S</option>
	<option value="306">KABUPATEN KUDUS</option>
	<option value="504">KABUPATEN KULON PROGO</option>
	<option value="234">KABUPATEN KUNINGAN</option>
	<option value="2411">KABUPATEN KUPANG</option>
	<option value="1713">KABUPATEN KUTAI BARAT</option>
	<option value="1711">KABUPATEN KUTAI KERTANEGA</option>
	<option value="1712">KABUPATEN KUTAI TIMUR</option>
	<option value="711">KABUPATEN LABUHAN BATU</option>
	<option value="1606">KABUPATEN LAMANDAU</option>
	<option value="415">KABUPATEN LAMONGAN</option>
	<option value="1504">KABUPATEN LANDAK</option>
	<option value="712">KABUPATEN LANGKAT</option>
	<option value="2812">KABUPATEN LEBAK</option>
	<option value="2423">KABUPATEN LEMBATA</option>
	<option value="808">KABUPATEN LIMA PULUH KOTO</option>
	<option value="3105">KABUPATEN LINGGA</option>
	<option value="2311">KABUPATEN LOMBOK BARAT</option>
	<option value="2312">KABUPATEN LOMBOK TENGAH</option>
	<option value="2313">KABUPATEN LOMBOK TIMUR</option>
	<option value="426">KABUPATEN LUMAJANG</option>
	<option value="1810">KABUPATEN LUWU</option>
	<option value="1826">KABUPATEN LUWU TIMUR</option>
	<option value="1811">KABUPATEN LUWU UTARA</option>
	<option value="713">KABUPATEN MADINA</option>
	<option value="431">KABUPATEN MADIUN</option>
	<option value="326">KABUPATEN MAGELANG</option>
	<option value="418">KABUPATEN MAGETAN</option>
	<option value="235">KABUPATEN MAJALENGKA</option>
	<option value="3205">KABUPATEN MAJENE</option>
	<option value="451">KABUPATEN MALANG</option>
	<option value="1707">KABUPATEN MALINAU</option>
	<option value="2502">KABUPATEN MALUKU TENGAH</option>
	<option value="2507">KABUPATEN MALUKU TENGGARA</option>
	<option value="2505">KABUPATEN MALUKU TENGGARA</option>
	<option value="3203">KABUPATEN MAMASA</option>
	<option value="3202">KABUPATEN MAMUJU UTARA</option>
	<option value="2420">KABUPATEN MANGGARAI</option>
	<option value="2424">KABUPATEN MANGGARAI BARAT</option>
	<option value="3303">KABUPATEN MANOKWARI</option>
	<option value="2617">KABUPATEN MAPPI</option>
	<option value="1814">KABUPATEN MAROS</option>
	<option value="1512">KABUPATEN MELAWI</option>
	<option value="2603">KABUPATEN MERAUKE</option>
	<option value="2608">KABUPATEN MIMIKA</option>
	<option value="2108">KABUPATEN MINAHASA INDUK</option>
	<option value="2104">KABUPATEN MINAHASA SEL</option>
	<option value="2107">KABUPATEN MINAHASA UTARA</option>
	<option value="421">KABUPATEN MOJOKERTO</option>
	<option value="2008">KABUPATEN MOROWALI</option>
	<option value="1905">KABUPATEN MUNA</option>
	<option value="1614">KABUPATEN MURUNG RAYA</option>
	<option value="2619">KABUPATEN NABIRE</option>
	<option value="616">KABUPATEN NAGAN RAYA</option>
	<option value="2426">KABUPATEN NAGEKEO</option>
	<option value="3104">KABUPATEN NATUNA</option>
	<option value="2419">KABUPATEN NGADA</option>
	<option value="423">KABUPATEN NGANJUK</option>
	<option value="417">KABUPATEN NGAWI</option>
	<option value="714">KABUPATEN NIAS</option>
	<option value="725">KABUPATEN NIAS SELATAN</option>
	<option value="1706">KABUPATEN NUNUKAN</option>
	<option value="422">KABUPATEN PACITAN</option>
	<option value="727">KABUPATEN PADANG LAWAS</option>
	<option value="809">KABUPATEN PADANG PARIAMAN</option>
	<option value="722">KABUPATEN PAKPAK BARAT</option>
	<option value="435">KABUPATEN PAMEKASAN</option>
	<option value="2811">KABUPATEN PANDEGLANG</option>
	<option value="1815">KABUPATEN PANGKEP</option>
	<option value="2607">KABUPATEN PANIAI</option>
	<option value="2009">KABUPATEN PARIMO</option>
	<option value="810">KABUPATEN PASAMAN</option>
	<option value="818">KABUPATEN PASAMAN BARAT</option>
	<option value="1702">KABUPATEN PASIR</option>
	<option value="471">KABUPATEN PASURUAN</option>
	<option value="308">KABUPATEN PATI</option>
	<option value="728">KABUPATEN PDG LAWAS UTARA</option>
	<option value="2612">KABUPATEN PEG. BINTANG</option>
	<option value="316">KABUPATEN PEKALONGAN</option>
	<option value="908">KABUPATEN PELALAWAN</option>
	<option value="317">KABUPATEN PEMALANG</option>
	<option value="1703">KABUPATEN PENAJAM</option>
	<option value="811">KABUPATEN PESISIR SELATAN</option>
	<option value="611">KABUPATEN PIDIE</option>
	<option value="622">KABUPATEN PIDIE JAYA</option>
	<option value="1816">KABUPATEN PINRANG</option>
	<option value="2904">KABUPATEN POHUWATO</option>
	<option value="3204">KABUPATEN POLEWALI</option>
	<option value="419">KABUPATEN PONOROGO</option>
	<option value="1502">KABUPATEN PONTIANAK</option>
	<option value="2006">KABUPATEN POSO</option>
	<option value="481">KABUPATEN PROBOLINGGO</option>
	<option value="1609">KABUPATEN PULANG PISAU</option>
	<option value="2609">KABUPATEN PUNCAK JAYA</option>
	<option value="322">KABUPATEN PURBALINGGA</option>
	<option value="222">KABUPATEN PURWAKARTA</option>
	<option value="328">KABUPATEN PURWOREJO</option>
	<option value="3307">KABUPATEN RAJA AMPAT</option>
	<option value="309">KABUPATEN REMBANG</option>
	<option value="3103">KABUPATEN RIAU KEPULAUAN</option>
	<option value="910">KABUPATEN ROKAN HILIR</option>
	<option value="909">KABUPATEN ROKAN HULU</option>
	<option value="2425">KABUPATEN ROTE NDAO</option>
	<option value="303">KABUPATEN SALATIGA</option>
	<option value="1505">KABUPATEN SAMBAS</option>
	<option value="723">KABUPATEN SAMOSIR</option>
	<option value="434">KABUPATEN SAMPANG</option>
	<option value="1511">KABUPATEN SANGGAU</option>
	<option value="2105">KABUPATEN SANGIHE</option>
	<option value="2610">KABUPATEN SARMI</option>
	<option value="812">KABUPATEN SAWAH LUNTO SJJ</option>
	<option value="1510">KABUPATEN SEKADAU</option>
	<option value="1818">KABUPATEN SELAYAR</option>
	<option value="302">KABUPATEN SEMARANG</option>
	<option value="2508">KABUPATEN SERAM BAGIAN BAR</option>
	<option value="2503">KABUPATEN SERAM BAGIAN TIM</option>
	<option value="2809">KABUPATEN SERANG</option>
	<option value="1604">KABUPATEN SERUYAN</option>
	<option value="911">KABUPATEN SIAK</option>
	<option value="412">KABUPATEN SIDOARJO</option>
	<option value="1819">KABUPATEN SIDRAP</option>
	<option value="2416">KABUPATEN SIKKA</option>
	<option value="715">KABUPATEN SIMALUNGUN</option>
	<option value="612">KABUPATEN SIMEULEU</option>
	<option value="613">KABUPATEN SINGKIL</option>
	<option value="1820">KABUPATEN SINJAI</option>
	<option value="1509">KABUPATEN SINTANG</option>
	<option value="429">KABUPATEN SITUBONDO</option>
	<option value="502">KABUPATEN SLEMAN</option>
	<option value="813">KABUPATEN SOLOK</option>
	<option value="819">KABUPATEN SOLOK SELATAN</option>
	<option value="1821">KABUPATEN SOPPENG</option>
	<option value="3302">KABUPATEN SORONG</option>
	<option value="3306">KABUPATEN SORONG SELATAN</option>
	<option value="331">KABUPATEN SRAGEN</option>
	<option value="508">KABUPATEN SRAGEN</option>
	<option value="232">KABUPATEN SUBANG</option>
	<option value="217">KABUPATEN SUKABUMI</option>
	<option value="1607">KABUPATEN SUKAMARA</option>
	<option value="511">KABUPATEN SUKOHARJO</option>
	<option value="334">KABUPATEN SUKOHARJO</option>
	<option value="2422">KABUPATEN SUMBA BARAT</option>
	<option value="2428">KABUPATEN SUMBA TENGAH</option>
	<option value="2421">KABUPATEN SUMBA TIMUR</option>
	<option value="2316">KABUPATEN SUMBAWA</option>
	<option value="2317">KABUPATEN SUMBAWA BARAT</option>
	<option value="225">KABUPATEN SUMEDANG</option>
	<option value="436">KABUPATEN SUMENEP</option>
	<option value="2620">KABUPATEN SUPIORI</option>
	<option value="1409">KABUPATEN TABALONG</option>
	<option value="2217">KABUPATEN TABANAN</option>
	<option value="1822">KABUPATEN TAKALAR</option>
	<option value="2106">KABUPATEN TALAUD</option>
	<option value="1823">KABUPATEN TANA TORAJA</option>
	<option value="1406">KABUPATEN TANAH BUMBU</option>
	<option value="814">KABUPATEN TANAH DATAR</option>
	<option value="1404">KABUPATEN TANAH LAUT</option>
	<option value="2808">KABUPATEN TANGERANG</option>
	<option value="717">KABUPATEN TAPANULI SELATA</option>
	<option value="716">KABUPATEN TAPANULI TENGAH</option>
	<option value="718">KABUPATEN TAPANULI UTARA</option>
	<option value="1408">KABUPATEN TAPIN</option>
	<option value="228">KABUPATEN TASIKMALAYA</option>
	<option value="313">KABUPATEN TEGAL</option>
	<option value="3308">KABUPATEN TELUK BINTUNI</option>
	<option value="3309">KABUPATEN TELUK WONDAMA</option>
	<option value="327">KABUPATEN TEMANGGUNG</option>
	<option value="2412">KABUPATEN TIM TGH SELATAN</option>
	<option value="2413">KABUPATEN TIM TGH UTARA</option>
	<option value="719">KABUPATEN TOBA SAMOSIR</option>
	<option value="2010">KABUPATEN TOJO UNA-UNA</option>
	<option value="2614">KABUPATEN TOLIKARA</option>
	<option value="2003">KABUPATEN TOLI-TOLI</option>
	<option value="425">KABUPATEN TRENGGALEK</option>
	<option value="416">KABUPATEN TUBAN</option>
	<option value="424">KABUPATEN TULUNGAGUNG</option>
	<option value="1824">KABUPATEN WAJO</option>
	<option value="1910">KABUPATEN WAKATOBI</option>
	<option value="2615">KABUPATEN WAROPEN</option>
	<option value="335">KABUPATEN WONOGIRI</option>
	<option value="512">KABUPATEN WONOGIRI</option>
	<option value="324">KABUPATEN WONOSOBO</option>
	<option value="2613">KABUPATEN YAHUKIMO</option>
	<option value="2606">KABUPATEN YAPEN WAROPEN</option>
	<option value="1206">KAUR</option>
	<option value="1208">KEPAHYANG</option>
	<option value="1010">KERINCI</option>
	<option value="601">KODYA BANDA ACEH</option>
	<option value="1301">KODYA BANDAR LAMPUNG</option>
	<option value="223">KODYA BANDUNG</option>
	<option value="3101">KODYA BATAM</option>
	<option value="1906">KODYA BAU-BAU</option>
	<option value="219">KODYA BEKASI</option>
	<option value="1201">KODYA BENGKULU</option>
	<option value="702">KODYA BINJAI</option>
	<option value="460">KODYA BLITAR</option>
	<option value="214">KODYA BOGOR</option>
	<option value="802">KODYA BUKIT TINGGI</option>
	<option value="2810">KODYA CILEGON</option>
	<option value="230">KODYA CIREBON</option>
	<option value="2210">KODYA DENPASAR</option>
	<option value="213">KODYA DEPOK</option>
	<option value="902">KODYA DUMAI</option>
	<option value="2901">KODYA GORONTALO</option>
	<option value="102">KODYA JAKARTA BARAT</option>
	<option value="101">KODYA JAKARTA PUSAT</option>
	<option value="103">KODYA JAKARTA SELATA</option>
	<option value="104">KODYA JAKARTA TIMUR</option>
	<option value="105">KODYA JAKARTA UTARA</option>
	<option value="1001">KODYA JAMBI</option>
	<option value="440">KODYA KEDIRI</option>
	<option value="1901">KODYA KENDARI</option>
	<option value="2410">KODYA KUPANG</option>
	<option value="430">KODYA MADIUN</option>
	<option value="325">KODYA MAGELANG</option>
	<option value="1801">KODYA MAKASSAR</option>
	<option value="450">KODYA MALANG</option>
	<option value="3201">KODYA MAMUJU</option>
	<option value="2101">KODYA MANADO</option>
	<option value="2310">KODYA MATARAM</option>
	<option value="701">KODYA MEDAN</option>
	<option value="420">KODYA MOJOKERTO</option>
	<option value="704">KODYA P SIANTAR</option>
	<option value="720">KODYA P SIDEMPUAN</option>
	<option value="801">KODYA PADANG</option>
	<option value="805">KODYA PADANG PANJANG</option>
	<option value="1109">KODYA PAGAR ALAM</option>
	<option value="1101">KODYA PALEMBANG</option>
	<option value="1825">KODYA PALOPO</option>
	<option value="2001">KODYA PALU</option>
	<option value="2701">KODYA PANGKAL PINANG</option>
	<option value="1802">KODYA PAREPARE</option>
	<option value="470">KODYA PASURUAN</option>
	<option value="803">KODYA PAYAKUMBUH</option>
	<option value="315">KODYA PEKALONGAN</option>
	<option value="901">KODYA PEKAN BARU</option>
	<option value="480">KODYA PROBOLINGGO</option>
	<option value="602">KODYA SABANG</option>
	<option value="804">KODYA SAWAH LUNTO</option>
	<option value="705">KODYA SIBOLGA</option>
	<option value="216">KODYA SUKABUMI</option>
	<option value="410">KODYA SURABAYA</option>
	<option value="329">KODYA SURAKARTA</option>
	<option value="2807">KODYA TANGERANG</option>
	<option value="227">KODYA TASIKMALAYA</option>
	<option value="703">KODYA TEBING TINGGI</option>
	<option value="706">KODYA TJ BALAI</option>
	<option value="2109">KODYA TOMOHON</option>
	<option value="501">KODYA YOGYAKARTA</option>
	<option value="2102">KODYA. BITUNG</option>
	<option value="2501">KOTA AMBON</option>
	<option value="1701">KOTA BALIKPAPAN</option>
	<option value="1403">KOTA BANJAR BARU</option>
	<option value="1401">KOTA BANJARMASIN</option>
	<option value="2318">KOTA BIMA</option>
	<option value="1710">KOTA BONTANG</option>
	<option value="2601">KOTA JAYAPURA</option>
	<option value="1111">KOTA L. LINGGAU</option>
	<option value="615">KOTA LANGSA</option>
	<option value="614">KOTA LHOK SEUMAWE</option>
	<option value="1601">KOTA PALANGKARAYA</option>
	<option value="815">KOTA PARIAMAN</option>
	<option value="1501">KOTA PONTIANAK</option>
	<option value="1709">KOTA SAMARINDA</option>
	<option value="1506">KOTA SINGKAWANG</option>
	<option value="816">KOTA SOLOK</option>
	<option value="3301">KOTA SORONG</option>
	<option value="623">KOTA SUBULUSSALAM</option>
	<option value="3106">KOTA TANJUNG PINANG</option>
	<option value="1704">KOTA TARAKAN</option>
	<option value="3001">KOTA TERNATE</option>
	<option value="3006">KOTA TIDORE KEPULAUA</option>
	<option value="1106">LAHAT</option>
	<option value="1310">LAMPUNG BARAT</option>
	<option value="1307">LAMPUNG SELATAN</option>
	<option value="1308">LAMPUNG TENGAH</option>
	<option value="1309">LAMPUNG TIMUR</option>
	<option value="1306">LAMPUNG UTARA</option>
	<option value="1209">LEBONG</option>
	<option value="1002">MERANGIN</option>
	<option value="1302">METRO</option>
	<option value="1104">MUARA ENIM</option>
	<option value="1004">MUARA JAMBI</option>
	<option value="1207">MUKO-MUKO</option>
	<option value="1102">MUSI BANYUASIN</option>
	<option value="1107">MUSI RAWAS</option>
	<option value="1112">OGAN ILIR</option>
	<option value="1103">OGAN KOMERING ILIR</option>
	<option value="1105">OGAN KOMERING ULU</option>
	<option value="1114">OGAN KOMERINGULU SEL</option>
	<option value="1113">OGAN KOMERINGULU TIM</option>
	<option value="1108">PRABUMULIH</option>
	<option value="1202">REJANG LEBONG</option>
	<option value="1006">SAROLANGUN</option>
	<option value="1205">SELUMA</option>
	<option value="301">SEMARANG KOTA</option>
	<option value="721">SERDANG BEDAGAI</option>
	<option value="1303">TANGGAMUS</option>
	<option value="1008">TANJUNG JABUNG BARAT</option>
	<option value="1007">TANJUNG JABUNG TIMUR</option>
	<option value="1005">TEBO</option>
	<option value="312">TEGAL KODIA</option>
	<option value="1304">TULANG BAWANG</option>
	<option value="1305">WAY KANAN</option>
</select>
</td></tr>
<tr ><td>Kode pos perusahaan</td><td>:</td><td><input type="text" name="pos" required="required" id="tes"/></td></tr>
<tr ><td>Telepon perusahaan</td><td>:</td><td><input type="text" name="telp" required="required" /></td></tr>
<tr ><td>Fax. perusahaan</td><td>:</td><td><input type="text" name="fax" required="required"/></td></tr>
<tr ><td>Email perusahaan</td><td>:</td><td><input type="text" name="email" required="required"/></td></tr><br />
<tr ><td>Nama Pengurus</td><td>:</td><td><input type="text" name="pengurus" required="required"/></td></tr>
<tr ><td>Jabatan</td><td>:</td><td><input type="text" name="jabatan" required="required"/></td></tr>
<tr><td>pilih file untuk di upload</td><td>:</td><td><input name="userfile" type="file" />(.rar/.zip) <br /> </td>  </tr>   
<tr ><td></td><td></td><td><input type="submit" value="submit" /></td></tr>
</form></tr></table>

</div>
</div>